<%
  riak_cs_node_count = 4
  total_node_count = riak_cs_node_count + 1 # +1 for stanchion
  network_ip_base = "10.244.0"
  riak_ips = riak_cs_node_count.times.map { |n| "#{network_ip_base}.#{n*4 + 2}" }
  riak_seed_node_ip = riak_ips.first
  stanchion_ip = "#{network_ip_base}.#{riak_cs_node_count*4 + 2}"
%>

name: riak-cs-warden
director_uuid: PLACEHOLDER

releases:
- name: riak-cs
  version: latest

compilation:
  workers: 2
  network: riak-cs-network
  reuse_compilation_vms: true
  cloud_properties:
    name: random

update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 3

resource_pools:
- name: common
  network: riak-cs-network
  size: 5
  stemcell:
    name: bosh-stemcell
    version: latest
  cloud_properties:
    name: random

networks:
- name: riak-cs-network
  subnets:
<% (0..(total_node_count-1)).each do |i| %>
  - range: <%= "#{network_ip_base}.#{i*4}/30" %>
    reserved:
      - <%= "#{network_ip_base}.#{i*4 + 1}" %>
    static:
      - <%= "#{network_ip_base}.#{i*4 + 2}" %>
    cloud_properties:
      name: random
<% end %>
# these additional subnets are not used; they've been added as a workaround
# for this bug: https://github.com/cloudfoundry/bosh/issues/373
<% (total_node_count..(2*total_node_count-1)).each do |i| %>
  - range: <%= "#{network_ip_base}.#{i*4}/30" %>
    reserved:
      - <%= "#{network_ip_base}.#{i*4 + 1}" %>
    cloud_properties:
      name: random
<% end %>

jobs:
- name: riak-cs
  template:
  - riak
  - riak-cs
  instances: <%= riak_cs_node_count %>
  resource_pool: common
  networks:
  - name: riak-cs-network
    static_ips:
<% (0..(riak_cs_node_count-1)).each do |i| %>
    - <%= "#{network_ip_base}.#{i*4 + 2}" %>
<% end %>
  persistent_disk: 4096
- name: stanchion
  template: stanchion
  instances: 1
  resource_pool: common
  networks:
  - name: riak-cs-network
    static_ips:
    - <%= stanchion_ip %>
  persistent_disk: 4096

properties:
  riak:
    seed_node: <%= riak_seed_node_ip %>
  riak_cs:
    admin_key: "admin-key"
    admin_secret: "admin-secret"
  stanchion:
    ip: <%= stanchion_ip %>
