---
erlang/otp_src_R15B01.tar.gz:
  object_id: ec4d9eb6-e5e9-4c3f-898a-8915b09ed7ab
  sha: !binary |-
    YzZlMWYyZmFkOTY1ZGViMzY5NjE4NGMxZWUxNjQ3MmJjZWEyYmYyMg==
  size: 75592537
git/git-1.8.4.tar.gz:
  object_id: b5ca56c0-0753-4ee3-bc27-efe3361d04f3
  sha: !binary |-
    YTIzOGYyYjUyNzM2NWI4OTZiOGVjNDQ3YjNlNWFiNWQ3YjRhMmM1YQ==
  size: 4657745
riak/leveldb-1.3.0.zip:
  object_id: 27ff3106-8b1f-42c1-8b71-3ecea98cb50a
  sha: !binary |-
    NDg4M2ZhZmRiNDNhMDdmZGU2NzNiMzJiODc5YWM5OTg2ZjZkZWUxNg==
  size: 328314
riak/riak-1.3.1.tar.gz:
  object_id: f206d864-5c32-4833-b438-d2ddd0625885
  sha: !binary |-
    ZmMzNWMzY2Y3ZmU3ZjFlNGYxZDJkYWY5NmFiZGEzYjMwMDM3YmE2Mg==
  size: 12665196
riak-cs/riak-cs-1.4.4.tar.gz:
  object_id: 47fbbd39-daac-46aa-be25-e6829c19ca15
  sha: !binary |-
    ZmZmN2E0ZGIxMWFjZmEwMjA1MTRhOTcwZWZjZGM2NzUzZTFkZDU1Mw==
  size: 4755824
stanchion/stanchion-1.4.3.tar.gz:
  object_id: c9b67ad7-8403-4d30-89f1-ebe1c5e7e79b
  sha: !binary |-
    YjMyMmEwYjNiYjM4ZWQ5MGViZGY2YWI1ODE3ZTVkZTlmNDk4MGZjYQ==
  size: 3275695
ruby/bundler-1.2.1.gem:
  object_id: ed3423da-9ec2-4d1a-bfab-44214541f26c
  sha: !binary |-
    MGNiZTZhZDdhNDFmMDY0ZDZjMTFjMTA1ODQ2NWZmZmIxYmQ1ODA2OQ==
  size: 226816
ruby/ruby-1.9.3-p484.tar.gz:
  object_id: c5f41024-fb16-4c5e-bf97-4c5194039f4c
  sha: !binary |-
    NmFlODBmNDI0OTY4YjVjZTY2MWVlOWIyYmVlMWMyMWFkYzllZTY3Yw==
  size: 12576996
ruby/rubygems-1.8.24.tgz:
  object_id: 88fa7374-7705-485d-bb3c-0479f2391003
  sha: !binary |-
    MzBmMjcwNDdlNzRmNzk0MzExNzczNmEwZDNlMjI0OTk0ZmVlMDkwNQ==
  size: 380101
libyaml/yaml-0.1.4.tgz:
  object_id: df9428ab-fc85-4dfd-9e2b-29ab51292010
  sha: !binary |-
    ZTBlNWUwOTE5MmFiMTBhNjA3ZTNkYTI5NzBkYjQ5MjExOGY1NjBmMg==
  size: 471759
