---
erlang/otp_src_R15B01.tar.gz:
  object_id: 9e25ae47-d485-4431-8a22-426c8e4b55d6
  sha: !binary |-
    YzZlMWYyZmFkOTY1ZGViMzY5NjE4NGMxZWUxNjQ3MmJjZWEyYmYyMg==
  size: 75592537
riak/leveldb-1.3.0.zip:
  object_id: c6da0fc6-6e8b-4834-9708-af10faae791b
  sha: !binary |-
    NDg4M2ZhZmRiNDNhMDdmZGU2NzNiMzJiODc5YWM5OTg2ZjZkZWUxNg==
  size: 328314
riak/riak-1.3.1.tar.gz:
  object_id: 2076810f-901f-4d31-ac41-5152bd71edb4
  sha: !binary |-
    ZmMzNWMzY2Y3ZmU3ZjFlNGYxZDJkYWY5NmFiZGEzYjMwMDM3YmE2Mg==
  size: 12665196
git/git-1.8.4.tar.gz:
  object_id: 924395bd-e721-487c-9f32-b0653e2fdb3e
  sha: !binary |-
    YTIzOGYyYjUyNzM2NWI4OTZiOGVjNDQ3YjNlNWFiNWQ3YjRhMmM1YQ==
  size: 4657745
riak-cs/riak-cs-1.4.4.tar.gz:
  object_id: 7587462a-01c2-481d-a6fb-abe39165ef8a
  sha: !binary |-
    ZmZmN2E0ZGIxMWFjZmEwMjA1MTRhOTcwZWZjZGM2NzUzZTFkZDU1Mw==
  size: 4755824
stanchion/stanchion-1.4.3.tar.gz:
  object_id: f7e5432e-1cc9-48c0-8d84-be6793099b99
  sha: !binary |-
    YjMyMmEwYjNiYjM4ZWQ5MGViZGY2YWI1ODE3ZTVkZTlmNDk4MGZjYQ==
  size: 3275695
