---
name: riak-cs-service
director_uuid: (( merge ))

releases:
- name: riak-cs
  version: latest

compilation:
  workers: 2
  network: riak-cs-network
  reuse_compilation_vms: true
  cloud_properties: &vm_cloud_properties
    ram: 4096
    disk: 4096
    cpu: 2

update:
  canaries: 1
  canary_watch_time: 30000-240000
  update_watch_time: 30000-600000
  max_in_flight: 3

resource_pools:
- name: riak-pool
  network: riak-cs-network
  size: 5
  stemcell:
    name: bosh-vsphere-esxi-ubuntu
    version: '1266'
  cloud_properties: *vm_cloud_properties
- name: broker-pool
  network: riak-cs-network
  size: 1
  stemcell:
    name: bosh-vsphere-esxi-ubuntu
    version: '1266'
  cloud_properties:
    ram: 512
    disk: 4096
    cpu: 2

networks:
- name: riak-cs-network
  subnets:
  - range: 10.0.0.0/24
    gateway: 10.0.0.1
    dns:
    - 10.0.0.3
    - 8.8.8.8
    static:
    - 10.0.0.50
    - 10.0.0.51
    - 10.0.0.52
    - 10.0.0.53
    - 10.0.0.54
    - 10.0.0.55
    reserved:
    - 10.0.0.2-10.0.0.49
    - 10.0.0.60-10.0.0.254
    cloud_properties:
      name: one # name of the Vsphere VLAN that you're deploying to

jobs:
- name: riak-cs
  template:
  - riak
  - riak-cs
  instances: 4
  resource_pool: riak-pool
  networks:
  - name: riak-cs-network
    static_ips:
    - 10.0.0.50
    - 10.0.0.51
    - 10.0.0.52
    - 10.0.0.53
  persistent_disk: 4096
- name: stanchion
  template: stanchion
  instances: 1
  resource_pool: riak-pool
  networks:
  - name: riak-cs-network
    static_ips:
    - 10.0.0.54
  persistent_disk: 4096
- name: cf-riak-cs-broker
  template: cf-riak-cs-broker
  instances: 1
  resource_pool: broker-pool
  networks:
  - name: riak-cs-network
    static_ips:
    - 10.0.0.55

properties:
  riak:
    firewall_enabled: true
    seed_node: 10.0.0.50
    ips:
    - 10.0.0.50
    - 10.0.0.51
    - 10.0.0.52
    - 10.0.0.53
  riak_cs:
    admin_key: "admin-key"
    admin_secret: "admin-secret"
    ips:
    - 10.0.0.50
    - 10.0.0.51
    - 10.0.0.52
    - 10.0.0.53
  stanchion:
    ip: 10.0.0.54
  broker:
    port: 8080
    username: admin
    password: admin
